### PR TITLE
Add ARM 32-bit relocation types

### PR DESCRIPTION
**Pull request by marek-g**
Copy pasted from http://45.32.102.46/files/learning/elf_for_arm.pdf

### CODE REVIEW

**Comment by gz** [comment]
Thanks for the contribution, look like just needs a `cargo fmt` then this can be merged!

**Comment by gz** [comment]
Do you mind also re-creating these two tests for ARM: https://github.com/gz/rust-elfloader/blob/master/src/arch/aarch64/test.rs

**Comment by marek-g** [comment]
Thank you Gerd for your review!

> Do you mind also re-creating these two tests for ARM: https://github.com/gz/rust-elfloader/blob/master/src/arch/aarch64/test.rs

Yes, I think I can do it, but please forgive me that if it takes a few days as I'm in a middle of something. Thanks!!

**Comment by gz** [comment]
No worries at all thanks a lot!

**Comment by marek-g** [comment]
Hi @gz !

I tried to create tests as you asked. But I've failed.

I installed Ubuntu 16.04 and `arm-linux-gnueabi-gcc` (it's GCC 5). I compiled sample tests with:
```sh
arm-linux-gnueabi-gcc -o test.arm test.c -fPIC -fPIE
arm-linux-gnueabi-gcc -o test_nopie.arm test.c -no-pie
arm-linux-gnueabi-gcc -o tls.arm tls.c -fPIC -fPIE
```

All commands generated output binaries. Unfortunately, only "no-pie" test is correct. The other two resulted in non-relocable binaries I think. The `binary.is_pie()` returns 0 and there are no `R_ARM_RELATIVE` relocations inside. Only `R_ARM_GLOB_DAT`. I tried to add `-shared` parameter to compiler, but it didn't help.

To be honest, I'm not sure what's going on. I'm using your library to load and emulate existing binaries. I'm not sure how to properly build new ones.

Do you know what's going on and how to fix compile commands to get PIE binaries?

**Comment by gz** [comment]
Hi, I'm also not very familiar with 32-bit ARM so I don't really know what's going on but I can try it out this week then and see if I get it to produce a useful binary for tests :)

Thanks a lot for checking and doing all this work!

**Pull request merged**
